refactor: add context parameters to inner functions
cayleygraph/quad pull request #10
Opened 2023-05-24 23:23 UTC by paralin

Eliminate context.TODO instances and add context parameters to all long-lived operations for code consistency and better behavior when contexts may be canceled in the middle of a long-lived operation.

2023-07-24 07:05 UTC, dennwc requested changes
I checked the PR, and for now I don't see the point of this change, to be honest.

It adds context everywhere, but none of the functions use it. So what's the benefit of this additional argument then?

Probably the only one that could potentially benefit from it is the `Copy` and `ReadAll`. But even in that case, it's easy to implement externally: extend either `Reader` or `Writer`, save context in it. It's the same as with `io.Reader/io.Writer` - they don't have/need the context.

So for now I think this change will likely be rejected. Please let me know if I missed something.

2023-07-24 11:25 UTC, paralin commented
The context is used all over the place, previously TODO was used. There was a severe bug I found where a context cancelation would result in zero results being returned instead of context canceled errors. This was very hard to trace down and the reason I went to all the work to pass contexts down the tree. Storing contexts in structs is not recommended according to the Go guidelines: https://go.dev/blog/context-and-structs and I've experienced a ton of bugs caused by storing contexts in structs which supports the opinion in that article.

2023-07-24 11:49 UTC, dennwc commented
Your concern is definitely valid for iterators, but not sure why quads should be concerned :thinking:

2023-07-24 18:08 UTC, paralin commented
Anywhere that context.TODO was used previously, I now propagate a context parameter.

2023-07-25 07:31 UTC, dennwc commented
I checked this PR (to `quad` repo) and I see literally 0 `context.TODO` replaced. Your PR actually adds `context.Background` to places where none was previously.

So again, I don't see a strong argument to "poison" this package with context. It doesn't need one currently.

So I'm closing this for now. Context in `cayley`/`hidalgo` is a different story, though. There we should keep and propagate them.

2023-07-25 07:31 UTC, closed without merging

2023-07-25 15:55 UTC, paralin commented
@dennwc you haven't considered the case when someone implements a custom quad writer where WriteQuad may take some time. In my case I want to be able to cancel WriteQuad. Please consider this more carefully.

2023-07-26 11:11 UTC, dennwc commented
Still disagree, sorry.

Again, you don't expect context to be passed to every `Write/Read` in Go `io` package, do you? Instead, you get `http.NewRequestWithContext` that stores context internally and does all the magic under the hood.

Exact same approach was taken here: `quad` package must not be concerned with contexts. For that, `cayley` has the following method defined on every quad store:

```go
NewQuadWriter() (quad.WriteCloser, error)
```

If you want quad writes to be affected by the context cancellation, please file a PR that adds a new method:

```go
NewQuadWriterCtx(ctx context.Context) (quad.WriteCloser, error)
```

No need to touch `quad` package at all.

2023-07-26 15:02 UTC, paralin commented
That's okay, I'll maintain a fork. Thanks.